language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
 - composer install --prefer-dist

script: phpunit --configuration tests/phpunit.xml.dist

notifications:
  slack: erstellbar:Ny185e1y8I7XTCbFasTTevEn